# Generated by Django 3.1.7 on 2021-03-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20210315_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('img', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Shehata',
        ),
    ]
