# Generated by Django 3.1.7 on 2021-03-15 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20210315_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='id',
            new_name='Id',
        ),
    ]
