# Generated by Django 3.1.7 on 2021-03-18 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20210317_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_value', models.IntegerField(blank=True, null=True, verbose_name=range(0, 5))),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.rate'),
        ),
    ]
