# Generated by Django 3.1.7 on 2021-03-18 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20210318_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_rate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.rate'),
        ),
    ]
