# Generated by Django 3.1.7 on 2021-03-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20210318_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_actors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.actor'),
        ),
    ]
